<?php
$drivers = [  
'lewis-hamilton' => [
    'name' => 'Lewis Hamilton',
    'country' => 'Wielka Brytania',
    'team' => 'Mercedes',
    'championships' => 7,
    'seasons' => '2007 - obecnie',
    'best_achievement' => 'Mistrz Świata 2008, 2014, 2015, 2017, 2018, 2019, 2020',
    'image'=>"/OP/mojastrona/zdjecia/lewis_hamilton.jpg",
],
'max-verstappen' => [
    'name' => 'Max Verstappen',
    'country' => 'Holandia',
    'team' => 'Red Bull Racing',
    'championships' => 3,
    'seasons' => '2015 - obecnie',
    'best_achievement' => 'Mistrz Świata 2021, 2022, 2023',
    'image'=>"/OP/mojastrona/zdjecia/max_verstappen.jpg",
],
'valtteri-bottas' => [
    'name' => 'Valtteri Bottas',
    'country' => 'Finlandia',
    'team' => 'Sauber',
    'championships' => 0,
    'seasons' => '2013 - obecnie',
    'best_achievement' => 'Wicemistrz 2019, 2020',
    'image'=>"/OP/mojastrona/zdjecia/valteri_bottas.jpg",
],
'carlos-sainz' => [
    'name' => 'Carlos Sainz',
    'country' => 'Hiszpania',
    'team' => 'Ferrari',
    'championships' => 0,
    'seasons' => '2015 - obecnie',
    'best_achievement' => '1 wygrana w GP',
    'image'=>"/OP/mojastrona/zdjecia/carlos_sainz.jpg",
],
'lando-norris' => [
    'name' => 'Lando Norris',
    'country' => 'Wielka Brytania',
    'team' => 'McLaren',
    'championships' => 0,
    'seasons' => '2019 - obecnie',
    'best_achievement' => 'Podium w wyścigach',
    'image'=>"/OP/mojastrona/zdjecia/lando_norris.jpg",
],
'sergio-perez' => [
    'name' => 'Sergio Perez',
    'country' => 'Meksyk',
    'team' => 'Red Bull Racing',
    'championships' => 0,
    'seasons' => '2011 - obecnie',
    'best_achievement' => '3 miejsce w klasyfikacji 2022',
    'image'=>"/OP/mojastrona/zdjecia/sergio_perez.jpg",
],
'lance-stroll' => [
    'name' => 'Lance Stroll',
    'country' => 'Kanada',
    'team' => 'Aston Martin',
    'championships' => 0,
    'seasons' => '2017 - obecnie',
    'best_achievement' => 'Podium w wyścigach',
    'image'=>"/OP/mojastrona/zdjecia/lance_stroll.jpg",
],
'daniel-ricciardo' => [
    'name' => 'Daniel Ricciardo',
    'country' => 'Australia',
    'team' => 'AlphaTauri',
    'championships' => 0,
    'seasons' => '2011 - obecnie',
    'best_achievement' => '3 miejsce w klasyfikacji 2014, 2016',
    'image'=>"/OP/mojastrona/zdjecia/daniel_ricciardo.jpg",
],
'esteban-ocon' => [
    'name' => 'Esteban Ocon',
    'country' => 'Francja',
    'team' => 'Alpine',
    'championships' => 0,
    'seasons' => '2016 - obecnie',
    'best_achievement' => '1 wygrana w GP',
    'image'=>"/OP/mojastrona/zdjecia/esteban_ocon.jpg",
],
'charles-leclerc' => [
    'name' => 'Charles Leclerc',
    'country' => 'Monako',
    'team' => 'Ferrari',
    'championships' => 0,
    'seasons' => '2018 - obecnie',
    'best_achievement' => '2 miejsce w klasyfikacji 2022',
    'image'=>"/OP/mojastrona/zdjecia/charles_leclerc.jpg",
],
'sebastian-vettel' => [
    'name' => 'Sebastian Vettel',
    'country' => 'Niemcy',
    'team' => 'Aston Martin',
    'championships' => 4,
    'seasons' => '2007 - 2022',
    'best_achievement' => 'Mistrz Świata 2010, 2011, 2012, 2013',
    'image'=>"/OP/mojastrona/zdjecia/sebastian_vettel.jpg",
],
'george-russell' => [
    'name' => 'George Russell',
    'country' => 'Wielka Brytania',
    'team' => 'Mercedes',
    'championships' => 0,
    'seasons' => '2019 - obecnie',
    'best_achievement' => '1 wygrana w GP',
    'image'=>"/OP/mojastrona/zdjecia/george_russell.jpg",
],
'nicholas-latifi' => [
    'name' => 'Nicholas Latifi',
    'country' => 'Kanada',
    'team' => 'Williams',
    'championships' => 0,
    'seasons' => '2020 - 2022',
    'best_achievement' => 'Bez punktów',
    'image'=>"/OP/mojastrona/zdjecia/nicholas_latifi.jpg",
],
'pierre-gasly' => [
    'name' => 'Pierre Gasly',
    'country' => 'Francja',
    'team' => 'Alpine',
    'championships' => 0,
    'seasons' => '2017 - obecnie',
    'best_achievement' => '1 wygrana w GP',
    'image'=>"/OP/mojastrona/zdjecia/pierre_gasly.jpg",
],
'daniil-kvyat' => [
    'name' => 'Daniil Kvyat',
    'country' => 'Rosja',
    'team' => 'AlphaTauri',
    'championships' => 0,
    'seasons' => '2014 - 2020',
    'best_achievement' => 'Podium w wyścigach',
    'image'=>"/OP/mojastrona/zdjecia/daniil_kvyat.jpg",
],
'kimi-raikkonen' => [
    'name' => 'Kimi Räikkönen',
    'country' => 'Finlandia',
    'team' => 'Alfa Romeo',
    'championships' => 1,
    'seasons' => '2001 - 2021',
    'best_achievement' => 'Mistrz Świata 2007',
    'image'=>"/OP/mojastrona/zdjecia/kimi_raikkonen.jpg",
],
'antonio-giovinazzi' => [
    'name' => 'Antonio Giovinazzi',
    'country' => 'Włochy',
    'team' => 'Alfa Romeo',
    'championships' => 0,
    'seasons' => '2017, 2019 - 2021',
    'best_achievement' => 'Punkty w wyścigach',
    'image'=>"/OP/mojastrona/zdjecia/antonio_giovinazzi.jpg",
],
'kevin-magnussen' => [
    'name' => 'Kevin Magnussen',
    'country' => 'Dania',
    'team' => 'Haas',
    'championships' => 0,
    'seasons' => '2014 - 2020, 2022 - obecnie',
    'best_achievement' => 'Podium w wyścigach',
    'image'=> "/OP/mojastrona/zdjecia/kevin_magnussen.jpg",
],
'romain-grosjean' => [
    'name' => 'Romain Grosjean',
    'country' => 'Francja',
    'team' => 'Haas',
    'championships' => 0,
    'seasons' => '2009, 2012 - 2020',
    'best_achievement' => 'Podium w wyścigach',
    'image'=> "/OP/mojastrona/zdjecia/romain_grosjean.jpg",
],
'fernando-alonso' => [
    'name' => 'Fernando Alonso',
    'country' => 'Hiszpania',
    'team' => 'Aston Martin',
    'championships' => 2,
    'seasons' => '2001 - 2018, 2021 - obecnie',
    'best_achievement' => 'Mistrz Świata 2005, 2006',
    'image'=> "/OP/mojastrona/zdjecia/fernando_alonso.jpg",
],
'yuki-tsunoda' => [
    'name' => 'Yuki Tsunoda',
    'country' => 'Japonia',
    'team' => 'AlphaTauri',
    'championships' => 0,
    'seasons' => '2021 - obecnie',
    'best_achievement' => 'Punkty w wyścigach',
    'image'=> "/OP/mojastrona/zdjecia/yuki_tsunoda.jpg",
],
'mick-schumacher' => [
    'name' => 'Mick Schumacher',
    'country' => 'Niemcy',
    'team' => 'Haas',
    'championships' => 0,
    'seasons' => '2021 - 2022',
    'best_achievement' => 'Punkty w wyścigach',
    'image'=> "/OP/mojastrona/zdjecia/mick_schumacher.jpg",
],
'nikita-mazepin' => [
    'name' => 'Nikita Mazepin',
    'country' => 'Rosja',
    'team' => 'Haas',
    'championships' => 0,
    'seasons' => '2021',
    'best_achievement' => 'Bez punktów',
    'image'=> "/OP/mojastrona/zdjecia/nikita_mazepin.jpg",
],
'zhou-guanyu' => [
    'name' => 'Zhou Guanyu',
    'country' => 'Chiny',
    'team' => 'Sauber',
    'championships' => 0,
    'seasons' => '2022 - obecnie',
    'best_achievement' => 'Punkty w wyścigach',
    'image'=> "/OP/mojastrona/zdjecia/zhou_guanyu.jpg",
],
'nyck-de-vries' => [
    'name' => 'Nyck de Vries',
    'country' => 'Holandia',
    'team' => 'AlphaTauri',
    'championships' => 0,
    'seasons' => '2023',
    'best_achievement' => 'Punkty w GP',
    'image'=> "/OP/mojastrona/zdjecia/nyck_de_vries.jpg",
],
'oscar-piastri' => [
    'name' => 'Oscar Piastri',
    'country' => 'Australia',
    'team' => 'McLaren',
    'championships' => 0,
    'seasons' => '2023 - obecnie',
    'best_achievement' => 'Podium w GP',
    'image'=> "/OP/mojastrona/zdjecia/oscar_piastri.jpg",
],
'nico-hulkenberg' => [
    'name' => 'Nico Hülkenberg',
    'country' => 'Niemcy',
    'team' => 'Haas',
    'championships' => 0,
    'seasons' => '2010 - 2020, 2023 - obecnie',
    'best_achievement' => 'Najlepsze 4 miejsce w GP',
    'image'=> "/OP/mojastrona/zdjecia/nico_hulkenberg.jpg",
],
'logan-sargeant' => [
    'name' => 'Logan Sargeant',
    'country' => 'USA',
    'team' => 'Williams',
    'championships' => 0,
    'seasons' => '2023 - obecnie',
    'best_achievement' => 'Punkty w GP',
    'image'=> "/OP/mojastrona/zdjecia/logan_sargeant.jpg",
],
'liam-lawson' => [
    'name' => 'Liam Lawson',
    'country' => 'Nowa Zelandia',
    'team' => 'AlphaTauri',
    'championships' => 0,
    'seasons' => '2023 (jako zmiennik)',
    'best_achievement' => 'Punkty w GP',
    'image'=> "/OP/mojastrona/zdjecia/liam_lawson.jpg",
],
];
